# Generated by Django 5.0.6 on 2024-07-07 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadstatus",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("dbf83436-9972-4213-82c5-f0b705522a84"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("86be5635-2ee5-4532-8305-f53c3b50f555"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
