# Generated by Django 5.0.6 on 2024-07-07 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("153d9e40-6044-4393-b4ad-e7a4e4a09d70"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("units", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("9452a8d0-d401-43a2-9198-7404469d2f76"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ingredients", models.ManyToManyField(to="Food_POS.ingredient")),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("0812a7c6-543d-47ac-ae9c-fd9c62cfe312"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("include_tax", models.BooleanField(default=True)),
                ("items", models.ManyToManyField(to="Food_POS.item")),
            ],
        ),
    ]
