# Generated by Django 5.0.6 on 2024-07-07 23:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Food_POS", "0002_alter_ingredient_id_alter_item_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2dbc79d1-44f4-428b-a660-b482732624ae"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a1754a3d-137d-462c-af6f-16ee89ba5739"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5a8b622d-07a1-4f2a-bc6e-aacab60e50ad"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
